### ISSUE TITLE
Criação de parâmetros avaliativos

### ISSUE THREAD

**Issue by gsampaio-rh** [firefighters-sre/docs#2]
[ ] Adicionar uma lista de critérios para avaliação das atividades (e.g. Essa atividade ao final deve conter com...)

**Comment by realjoleauna** [comment]
Challenge 1 não deve caber em uma folha com os dois mapas
solução: podemos dividir em duas folhas, uma com cada parte do desafio. primeiro entregamos uma e depois entregamos a outra. 
vai fortalecer ainda mais a ideia de dividir a atividade em partes.
