### ISSUE TITLE
Revisão atividade 1

### ISSUE THREAD

**Issue by realjoleauna** [firefighters-sre/docs#76]
Tranformar a atividade em algo mais dinâmico.

- [ ] Adicionar Chaos Engineering
- [ ] Achar uma maneira de metrificar os resultados

**Comment by gsampaio-rh** [comment]
Vamos adicionar os seguintes eventos surpresas:

Mudança do Número de Pessoas: O número de pessoas nas salas aumenta ou diminui inesperadamente, afetando a dinâmica da evacuação.
Escada 1 Quebrada: Uma das principais escadas de emergência está inacessível, forçando a equipe a usar rotas alternativas.
Escada 2 Quebrada: Uma das principais escadas de emergência está inacessível, forçando a equipe a usar rotas alternativas.
(Aumento do fogo) Passagem Bloqueada: Uma rota de evacuação principal está bloqueada por obstáculos inesperados (como móveis ou equipamentos).
Falha no Sistema de Alarme e Comunicação: O sistema de alarme de incêndio falha ou as comunicações internas são interrompidas, dificultando a disseminação de informações críticas.
